---

- hosts: all
  become: false
  tasks: 
  
        #- name: kinit
        #  local_action: command echo "xxxxxxxxxxx" | kinit -l 7d -r 7d -pf user1@DOMAIN.ORG
  
        - name: ping
          ping:
          when: ansible_os_family == "RedHat"
  
        - name: win ping
          win_ping:
          when: not(ansible_os_family == "RedHat")
